### ISSUE TITLE
Checkout action on Mac machine

### ISSUE THREAD

**Issue by blane1988** [actions/checkout#576]
Hello,

Is anyone experiencing Checkout failure when the runner is on a Mac machine? It works fine on Linux machines.

It started happening today.

```
error: cannot lock ref 'refs/remotes/origin/<redacted>/enhancement/codeRefactoring': 'refs/remotes/origin/<redacted>/enhancement' exists; cannot create 'refs/remotes/origin/<redacted>/enhancement/codeRefactoring'
 ! [new branch]            <redacted>/enhancement/codeRefactoring -> origin/<redacted>/enhancement/codeRefactoring  (unable to update local ref)
error: some local refs could not be updated; try running
```

and

```
Error: Git fetch failed with exit code: 1
##[debug]   at GitHub.Runner.Plugins.Repository.v1_0.GitHubSourceProvider.GetSourceAsync(RunnerActionPluginExecutionContext executionContext, String repositoryPath, String repoFullName, String sourceBranch, String sourceVersion, Boolean clean, String submoduleInput, Int32 fetchDepth, Boolean gitLfsSupport, String accessToken, CancellationToken cancellationToken)
##[debug]   at GitHub.Runner.Plugins.Repository.v1_0.CheckoutTask.RunAsync(RunnerActionPluginExecutionContext executionContext, CancellationToken token)
##[debug]   at GitHub.Runner.PluginHost.Program.Main(String[] args)
Error: Exit code 1 returned from process: file name '/Users/runner/runners/2.280.3/bin/Runner.PluginHost', arguments 'action "GitHub.Runner.Plugins.Repository.v1_0.CheckoutTask, Runner.Plugins"'.
##[debug]GitHub.Runner.Sdk.ProcessExitCodeException: Exit code 1 returned from process: file name '/Users/runner/runners/2.280.3/bin/Runner.PluginHost', arguments 'action 
```

**Comment by blane1988** [comment]
Issue: Two branches in the repo had similar initial paths that caused conflict. Case-insensitive as well.

testing/Enhancement (recently pushed)
testing/enhancement/codeRefactoring (months old)

Resolution: Deleted the older branch (testing/enhancement/codeRefactoring) and actions/checkout worked again.
