### ISSUE TITLE
Error: Parameter using node16 is not supported, use docker or node12 instead 

### ISSUE THREAD

**Issue by ogomozov-godaddy** [actions/checkout#711]
Update to commit a12a3943b4bdde767164f792f33f40b04645d846 (March 01) via dependabot caused error in this action
I believe it is somehow related to actions\runner, which is likely throws this error and being used by actions\checkout
Here is our code for this action:
```
   - name: Checkout Current Repo
        uses: actions/checkout@a12a3943b4bdde767164f792f33f40b04645d846
```

Here is the log
```
Download action repository 'actions/checkout@a12a3943b4bdde767164f792f33f40b04645d846' (SHA:a12a3943b4bdde767164f792f33f40b04645d846)
Error: System.ArgumentOutOfRangeException: Specified argument was out of the range of valid values. (Parameter ''using: node16' is not supported, use 'docker' or 'node12' instead.')
   at GitHub.Runner.Worker.ActionManifestManager.ConvertRuns(IExecutionContext executionContext, TemplateContext templateContext, TemplateToken inputsToken, String fileRelativePath, MappingToken outputs)
   at GitHub.Runner.Worker.ActionManifestManager.Load(IExecutionContext executionContext, String manifestFile)
Error: Fail to load actions/checkout/a12a3943b4bdde767164f792f33f40b04645d846/action.yml
```

**Comment by thboop** [comment]
Hey @ogomozov-godaddy, are you running on GHES or dotcom? This sounds like an out of date runner version, please pin to the `@v2` tag or the latest sha on that branch if you are unable to update your runner. We document the minimum runner version [here](https://github.com/actions/checkout#whats-new).

**Comment by ogomozov-godaddy** [comment]
we run Enterprise, but it is under github.com. Idk, which code of actions\runners we use. We also use custom self hosted runners, idk if it matters

**Comment by hutson** [comment]
We encountered a similar issue within our GitHub Enterprise Server deployment (Which uses self-hosted runners).

We're currently running GitHub Enterprise Server 3.3, but our repositories are receiving automated PRs to update them to `actions/checkout@3`.

Those PRs fail because of the Node 16 error mentioned above.

At the moment we're waiting to upgrade to 3.4, which should resolve the issue.

**Comment by shubhamdeodia** [comment]
Having the same issue

<img width="1436" alt="image" src="https://user-images.githubusercontent.com/55275771/169528818-6e5ab286-bf9c-4941-9839-9edb09170786.png">

**Comment by bitfrost** [comment]
Same,  intermittent.  Enterprise / github.com , self hosted runners

**Comment by rafael-leal-mccormack** [comment]
Also having this issue, are there any work arounds?

**Comment by IanKnighton** [comment]
Some time later...

I'm now seeing this issue on a handful of repos/workflows with self hosted runners. 

Would be cool to know what the issue is.

**Comment by LevanArabuli** [comment]
Any updates on this?

**Comment by HiptJo** [comment]
+1

**Comment by minhchienwikipedia** [comment]
any update?

**Comment by felixmattsson** [comment]
+1

**Comment by HiptJo** [comment]
The issue solved itself in some way or another for me - i have no idea, how it has been solved

I did perform an docker version update at some point, but i don't know if that really solved it - or if it has been solved in any other way.

**Comment by krush-fwtv** [comment]
On self-hosted runners, as soon as I add an SSH key or known-hosts, this problem is showing up for me
